# LabelEncoder
* sklearn.preprocessing.LabelEncoder
* fit(y)
> Fit label encoder.
* fit_tranFit label encoder.sform(y)
> Fit label encoder and return encoded labels.
* get_params([deep])
> Get parameters for this estimator.
* inverse_transform(y)
> Transform labels back to original encoding.
* set_params(**params)
> Set the parameters of this estimator.
* transform(y)
> Transform labels to normalized encoding.

In [7]:
from sklearn.preprocessing import LabelEncoder

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 label 인코딩 수행
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 :',labels)

인코딩 변환값 : [0 1 4 5 3 3 2 2]


In [8]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [9]:
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


## titanic_train.csv 전처리
- 판다스를 이용해서 csv 읽어 오기
- 필요한 칼러만 남기고 drop
- fillna를 활용하여 결측치 처리(mean)
- LabelEncoder를 활용하여 인코딩

> Titanic 데이터 전처리<br>
Survived, Sex, age, embarked 컬럼만 이용하려고 한다.<br>
피처는 sex, age, embarked 사용하고<br>
레이블은 survived 사용하여 지도학습을 하려고 한다.<br>
데이터의 전처리가 필요한 상황이라 데이터 전처리를 해야하는데 결측치가 관찰이 되어 결측치 처리를 해야하고 문자열이 보여서 인코딩을 해줘야한다.<br>
결측치는 평균값으로 인코딩은 labelencoding을 이용하여 처리한 결과를 데이터 프레임으로 출력<br>

In [18]:
import pandas as pd
df = pd.read_csv('C:/apps/ml/datasets/train.csv')
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [20]:
df = df[['Survived','Sex','Age','Embarked']]
# 쌤풀이 df.drop(columns=['PassengerId','Pclass','Name','SibSp','Parch','Ticket','Fare','Cabin'],inplace=True)

In [16]:
df

Survived     Sex   Age Embarked
0           0    male  22.0        S
1           1  female  38.0        C
2           1  female  26.0        S
3           1  female  35.0        S
4           0    male  35.0        S
..        ...     ...   ...      ...
886         0    male  27.0        S
887         1  female  19.0        S
888         0  female   NaN        S
889         1    male  26.0        C
890         0    male  32.0        Q

[891 rows x 4 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   Embarked  889 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [22]:
df.isna().sum()

Survived      0
Sex           0
Age         177
Embarked      2
dtype: int64

In [27]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

C:\Users\user\AppData\Local\Temp/ipykernel_22248/1841944837.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Age'] = df['Age'].fillna(df['Age'].mean())


In [31]:
df['Embarked'] = df['Embarked'].fillna('S')

C:\Users\user\AppData\Local\Temp/ipykernel_22248/1250008409.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = df['Embarked'].fillna('S')


In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       891 non-null    float64
 3   Embarked  891 non-null    object 
dtypes: float64(1), int64(1), object(2)
memory usage: 28.0+ KB


In [35]:
# Sex, Embarked encoding
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df['Sex'] = encoder.fit_transform(df['Sex'])
df['Embarked'] = encoder.fit_transform(df['Embarked'])
df

C:\Users\user\AppData\Local\Temp/ipykernel_22248/2540441645.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Sex'] = encoder.fit_transform(df['Sex'])
C:\Users\user\AppData\Local\Temp/ipykernel_22248/2540441645.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Embarked'] = encoder.fit_transform(df['Embarked'])


Survived  Sex  Age  Embarked
0           0    1   28         2
1           1    0   52         0
2           1    0   34         2
3           1    0   48         2
4           0    1   48         2
..        ...  ...  ...       ...
886         0    1   35         2
887         1    0   24         2
888         0    0   39         2
889         1    1   34         0
890         0    1   43         1

[891 rows x 4 columns]

# OneHotEncoder

In [39]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 먼저 숫자값으로 변환ㅇ르 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
# 2차원 데이터로 변환한다.
labels = labels.reshape(-1,1)# 전치 행렬

# 원-핫 인코딩 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_encoder = oh_encoder.transform(labels)
print('원-핫 인코딩 데이터')
print(oh_encoder.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_encoder.shape)



원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원
(8, 6)


In [45]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','선풍기','믹서','믹서']
one_encoder = OneHotEncoder()
items = np.array(items).reshape(-1,1)
data = one_encoder.fit_transform(items)
data.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [48]:
# titanic data에 적용
from sklearn.preprocessing import OneHotEncoder
df = pd.read_csv('C:/apps/ml/datasets/train.csv')
oneh_encoder = OneHotEncoder()
trans_data = oneh_encoder.fit_transform(df[['Sex']])
trans_data.toarray()

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

## pandas_get_dummies
pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)

In [3]:
import pandas as pd 
df = pd.read_csv('./datasets/train.csv')
df.drop(columns = ['PassengerId','Pclass','Name','SibSp', 'Parch','Ticket','Fare','Cabin'],inplace=True)
df['Age']  = df['Age'].fillna(df['Age'].mean() )
df['Embarked'] = df['Embarked'].fillna('S')

In [4]:
data = df.loc[:,'Embarked']

In [5]:
data

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [8]:
dummy_embark = pd.get_dummies(data)
dummy_embark

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [9]:
dummy_df = pd.get_dummies(df[['Sex','Embarked']])
dummy_df

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [10]:
dummy_df = pd.concat([df, dummy_df], axis=1)
dummy_df

Survived     Sex        Age Embarked  Sex_female  Sex_male  Embarked_C  \
0           0    male  22.000000        S           0         1           0   
1           1  female  38.000000        C           1         0           1   
2           1  female  26.000000        S           1         0           0   
3           1  female  35.000000        S           1         0           0   
4           0    male  35.000000        S           0         1           0   
..        ...     ...        ...      ...         ...       ...         ...   
886         0    male  27.000000        S           0         1           0   
887         1  female  19.000000        S           1         0           0   
888         0  female  29.699118        S           1         0           0   
889         1    male  26.000000        C           0         1           1   
890         0    male  32.000000        Q           0         1           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 9 columns]

In [12]:
dummy_df.drop(columns=['Sex','Embarked'],inplace=True)

In [13]:
dummy_df

Survived        Age  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
0           0  22.000000           0         1           0           0   
1           1  38.000000           1         0           1           0   
2           1  26.000000           1         0           0           0   
3           1  35.000000           1         0           0           0   
4           0  35.000000           0         1           0           0   
..        ...        ...         ...       ...         ...         ...   
886         0  27.000000           0         1           0           0   
887         1  19.000000           1         0           0           0   
888         0  29.699118           1         0           0           0   
889         1  26.000000           0         1           1           0   
890         0  32.000000           0         1           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 7 columns]